import type { NextPage } from "next";
import Head from "next/head";
import Cart from "@components/Cart/Cart";
import Products from "../components/Products/Products";
import Hello, { BackgroundColor } from "../components/Hello/Hello";
import Users from "../components/Users/Users";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Hello title="Hello Friend" background={BackgroundColor.blue} /> */}
        <Users />
        <div style={{ display: "flex" }}>
          <Products />
          <Cart />
        </div>
      </main>
    </div>
  );
};

export default Home;
